categories:
  # - name: "System Checks"
  #   steps:
  #     - check_operating_system
  #     - verify_current_user

  - name: "Package Management"
    steps:
      - install_homebrew_packages

  - name: 'Desktop Applications'
    steps:
      - install_desktop_apps

  - name: 'Fonts'
    steps:
      - install_fonts

  - name: 'Shell Tools'
    steps:
      - install_zplug
      - install_prezto

  - name: 'Configuration'
    steps:
      - configure_git

  - name: 'Development Environment'
    steps:
      - install_dev_env

  - name: 'Configuration Files'
    steps:
      - symlink_dotfiles

  # - name: "Configuration Files"
  #   steps:
  #     - setup_symlinks
  #     - configure_git

  # - name: "Demonstrations"
  #   steps:
  #     - show_current_date
  #     - hello_world_demo
  #     - slow_operation_demo
  #     - error_handling_demo
