tap 'homebrew/bundle'
tap 'neovim/neovim'
tap 'mas-cli/tap'
tap 'buo/cask-upgrade'
tap 'homebrew/cask-fonts'

# Build Tools
brew 'automake'
brew 'autoconf'
brew 'gpg'
brew 'libyaml'
brew 'libffi'
brew 'libxslt'
brew 'libtool'
brew 'unixodbc'
brew 'readline'
brew 'xz'
brew 'coreutils'
brew 'openssl'
brew 'jemalloc'
brew 'zlib'

# Development Tools
brew 'git'
brew 'tig' # git log
brew 'sqlite'
brew 'diff-so-fancy' # git diff
brew 'git-delta' # git diff
brew 'scmpuff' # git management
brew 'the_silver_searcher' # search
brew 'ripgrep' # search
brew 'jq' # json
brew 'awk'

# Formatters
brew 'shfmt'
brew 'stylua'

# Utitlies
brew 'zsh'
brew 'htop-osx'
brew 'wget'
brew 'tmux'
brew 'tmate'
brew 'tmux-mem-cpu-load'
brew 'reattach-to-user-namespace'
brew 'terminal-notifier'
brew 'ffmpeg'
brew 'rtmpdump'
# du replacement
brew 'ncdu'
# twitch livestreamer
brew 'streamlink'

brew 'tree'
# tree replacement
brew 'broot'
# Cat replacement
brew 'bat'
# Fuzzy search
brew 'fzf'
# ls replacement
brew 'exa'
# multiple concurrent downloads
brew 'aria2'
# symlink management
brew 'stow'
# find replacement
brew 'fd'

# Desktop Managers
brew 'koekeishiya/formulae/skhd'
brew 'yabai'

# Fonts
# Powerline Fonts
cask 'font-consolas-for-powerline'
cask 'font-menlo-for-powerline'
cask 'font-cascadia-mono-pl'

# Nerd Fonts
# https://github.com/ryanoasis/nerd-fonts
cask 'font-anonymice-nerd-font'
cask 'font-dejavu-sans-mono-nerd-font'
cask 'font-droid-sans-mono-nerd-font'
cask 'font-fira-code-nerd-font'
cask 'font-fira-mono-nerd-font'
cask 'font-go-mono-nerd-font'
cask 'font-iosevka-nerd-font'
cask 'font-jetbrains-mono-nerd-font'
cask 'font-liberation-nerd-font'
cask 'font-meslo-lg-nerd-font'
cask 'font-roboto-mono-nerd-font'
cask 'font-sauce-code-pro-nerd-font'
cask 'font-victor-mono-nerd-font'
cask 'font-blex-mono-nerd-font'
cask 'font-fantasque-sans-mono-nerd-font'


# Programming Fonts
cask 'font-input'
